package servers

// Filesystem home for extension-managed game servers: <dataDir>/servers/<id>.
// Everything stays inside that subtree (ContainedPath), files are capped,
// and destructive operations go through the caller's confirmation dialog.

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"Aether/pkg/fs"
)

// MaxServerFileBytes caps single file reads/writes inside a server dir.
const MaxServerFileBytes = 5 * 1024 * 1024

// ServerInfo describes one managed server directory.
type ServerInfo struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

var serverIDRe = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]{0,64}$`)

func serversRoot() (string, error) {
	root := filepath.Join(fs.GetDataDir(), "servers")
	if err := os.MkdirAll(root, 0755); err != nil {
		return "", err
	}
	return root, nil
}

func serverDir(id string) (string, error) {
	if !serverIDRe.MatchString(id) {
		return "", fmt.Errorf("invalid server id %q", id)
	}
	root, err := serversRoot()
	if err != nil {
		return "", err
	}
	return fs.ContainedPath(root, id)
}

func serverFile(id, rel string) (string, error) {
	dir, err := serverDir(id)
	if err != nil {
		return "", err
	}
	rel = filepath.FromSlash(strings.TrimSpace(rel))
	if rel == "" || rel == "." {
		return "", fmt.Errorf("file path is required")
	}
	return fs.ContainedPath(dir, rel)
}

// CreateServer creates servers/<id>/ with a starter server.properties.
func CreateServer(id, name string) (ServerInfo, error) {
	id = strings.ToLower(strings.TrimSpace(id))
	dir, err := serverDir(id)
	if err != nil {
		return ServerInfo{}, err
	}
	if st, err := os.Stat(dir); err == nil && st.IsDir() {
		// Check it's actually ours (has our marker) vs a stray dir?
		// Stray dirs are adopted: listing is directory-based.
		_ = st
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		return ServerInfo{}, err
	}
	if name == "" {
		name = id
	}
	props := filepath.Join(dir, "server.properties")
	if _, err := os.Stat(props); os.IsNotExist(err) {
		defaults := "# Generated by Aether\nmotd=" + sanitizeMOTD(name) + "\nserver-port=25565\nonline-mode=true\n"
		if err := os.WriteFile(props, []byte(defaults), 0644); err != nil {
			return ServerInfo{}, err
		}
	}
	return ServerInfo{ID: id, Name: name}, nil
}

func sanitizeMOTD(name string) string {
	var sb strings.Builder
	for _, r := range name {
		if r == '\n' || r == '\r' {
			sb.WriteByte(' ')
			continue
		}
		sb.WriteRune(r)
	}
	s := strings.TrimSpace(sb.String())
	if len(s) > 120 {
		s = s[:120]
	}
	if s == "" {
		s = "A Minecraft Server"
	}
	return s
}

// ListServers returns every servers/<id> directory.
func ListServers() ([]ServerInfo, error) {
	root, err := serversRoot()
	if err != nil {
		return nil, err
	}
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, err
	}
	var out []ServerInfo
	for _, e := range entries {
		if !e.IsDir() || !serverIDRe.MatchString(e.Name()) {
			continue
		}
		out = append(out, ServerInfo{ID: e.Name(), Name: e.Name()})
	}
	if out == nil {
		out = []ServerInfo{}
	}
	return out, nil
}

// DeleteServer removes servers/<id> entirely.
func DeleteServer(id string) error {
	dir, err := serverDir(id)
	if err != nil {
		return err
	}
	if _, err := os.Stat(dir); os.IsNotExist(err) {
		return fmt.Errorf("server %q does not exist", id)
	}
	return os.RemoveAll(dir)
}

// ReadServerFile returns a file inside servers/<id> as UTF-8 text.
// Binary-safe callers should use base64 themselves; configs are text.
func ReadServerFile(id, rel string) (string, error) {
	path, err := serverFile(id, rel)
	if err != nil {
		return "", err
	}
	st, err := os.Stat(path)
	if err != nil {
		return "", fmt.Errorf("file not found: %s", rel)
	}
	if st.IsDir() {
		return "", fmt.Errorf("%s is a directory", rel)
	}
	if st.Size() > MaxServerFileBytes {
		return "", fmt.Errorf("file exceeds the 5 MB limit")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// WriteServerFile writes base64-encoded content to a file inside
// servers/<id>, creating parent directories. Capped at 5 MiB.
func WriteServerFile(id, rel, base64Data string) error {
	path, err := serverFile(id, rel)
	if err != nil {
		return err
	}
	data, err := base64.StdEncoding.DecodeString(base64Data)
	if err != nil {
		return fmt.Errorf("invalid base64 data: %w", err)
	}
	if len(data) > MaxServerFileBytes {
		return fmt.Errorf("file exceeds the 5 MB limit")
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0644); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

// ReadInstanceServers parses <instance>/servers.dat (if present) into entries.
func ReadInstanceServers(instanceID string) ([]ServerEntry, error) {
	dir, err := fs.ContainedPath(filepath.Join(fs.GetDataDir(), "instances"), instanceID)
	if err != nil {
		return nil, err
	}
	data, err := os.ReadFile(filepath.Join(dir, "servers.dat"))
	if err != nil {
		if os.IsNotExist(err) {
			return []ServerEntry{}, nil
		}
		return nil, err
	}
	return ParseServersDat(data)
}
