// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {instance} from '../models';
import {auth} from '../models';
import {main} from '../models';
import {mojang} from '../models';
import {extensions} from '../models';
import {logger} from '../models';
import {settings} from '../models';
import {theme} from '../models';

export function CheckForUpdates():Promise<update.Info>;

export function ClearLogs():Promise<void>;

export function CreateInstance(arg1:string,arg2:string,arg3:string):Promise<instance.Instance>;

export function DeleteInstance(arg1:string):Promise<void>;

export function DownloadAndInstallExtension(arg1:string):Promise<boolean>;

export function DownloadAndUpdate():Promise<void>;

export function DownloadJavaRuntime(arg1:number):Promise<void>;

export function EquipProfileCape(arg1:string):Promise<void>;

export function GetAccounts():Promise<Array<auth.Account>>;

export function GetActiveAccount():Promise<auth.Account>;

export function GetActiveInstance():Promise<instance.Instance>;

export function GetActiveThemeAssets():Promise<Record<string, string>>;

export function GetActiveThemeCSS():Promise<string>;

export function GetAetherReleaseNotes():Promise<Array<main.AetherReleaseNote>>;

export function GetAvailableVersions(arg1:boolean):Promise<Array<string>>;

export function GetConnectivityStatus():Promise<mojang.ConnectivityStatus>;

export function GetExtensionSidebarPages():Promise<Array<Record<string, any>>>;

export function GetExtensionUpdates():Promise<Array<extensions.ExtensionUpdate>>;

export function GetExtensions():Promise<Array<extensions.Extension>>;

export function GetInstanceIcon(arg1:string):Promise<string>;

export function GetInstanceIcons():Promise<Record<string, string>>;

export function GetInstances():Promise<Array<instance.Instance>>;

export function GetJavaStatus():Promise<Array<main.JavaRuntimeStatus>>;

export function GetLauncherVersion():Promise<string>;

export function GetLogs():Promise<Array<logger.LogEntry>>;

export function GetMinecraftNews():Promise<Array<main.MinecraftNewsItem>>;

export function GetModLoaders():Promise<Array<main.ModLoaderInfo>>;

export function GetProfileCapes():Promise<Array<auth.CapeEntry>>;

export function GetProfileSkins():Promise<Array<auth.SkinEntry>>;

export function GetRecentScreenshots(arg1:number):Promise<Array<main.ScreenshotItem>>;

export function GetSettings():Promise<settings.GlobalSettings>;

export function GetThemes():Promise<Array<theme.Info>>;

export function HideProfileCape():Promise<void>;

export function InstallInstance(arg1:string):Promise<void>;

export function LaunchInstance(arg1:string):Promise<void>;

export function LaunchInstanceToServer(arg1:string,arg2:string,arg3:number):Promise<void>;

export function LaunchInstanceToWorld(arg1:string,arg2:string):Promise<void>;

export function ListInstanceWorlds(arg1:string):Promise<Array<instance.WorldInfo>>;

export function LoginOffline(arg1:string):Promise<auth.Account>;

export function OpenInstanceFolder(arg1:string):Promise<void>;

export function OpenScreenshot(arg1:string,arg2:string):Promise<void>;

export function OpenScreenshotsFolder(arg1:string):Promise<void>;

export function PickInstanceIcon(arg1:string):Promise<string>;

export function ReloadExtensions():Promise<void>;

export function RemoveAccount(arg1:string):Promise<void>;

export function RemoveInstanceIcon(arg1:string):Promise<void>;

export function ResolveExtensionConfirmation(arg1:string,arg2:boolean):Promise<void>;

export function SaveSettings(arg1:settings.GlobalSettings):Promise<void>;

export function SelectAndImportInstance():Promise<string>;

export function SelectAndInstallExtension():Promise<boolean>;

export function SelectAndInstallTheme():Promise<theme.InstallResult>;

export function SendExtensionMessage(arg1:string,arg2:Record<string, any>):Promise<void>;

export function SetActiveAccount(arg1:string):Promise<void>;

export function SetActiveTheme(arg1:string):Promise<void>;

export function StartMicrosoftAuth():Promise<auth.Account>;

export function UninstallExtension(arg1:string):Promise<void>;

export function UninstallTheme(arg1:string):Promise<void>;

export function UpdateExtension(arg1:string):Promise<extensions.ExtensionUpdate>;

export function UpdateInstance(arg1:instance.Instance):Promise<void>;

export function UploadProfileSkin(arg1:string,arg2:string):Promise<auth.SkinEntry>;

export function WindowChrome():Promise<string>;
