// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateInstance(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateInstance'](arg1, arg2, arg3);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function DownloadAndInstallExtension(arg1) {
  return window['go']['main']['App']['DownloadAndInstallExtension'](arg1);
}

export function DownloadJavaRuntime(arg1) {
  return window['go']['main']['App']['DownloadJavaRuntime'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetActiveAccount() {
  return window['go']['main']['App']['GetActiveAccount']();
}

export function GetActiveInstance() {
  return window['go']['main']['App']['GetActiveInstance']();
}

export function GetAvailableVersions(arg1) {
  return window['go']['main']['App']['GetAvailableVersions'](arg1);
}

export function GetExtensionSidebarPages() {
  return window['go']['main']['App']['GetExtensionSidebarPages']();
}

export function GetExtensionUpdates() {
  return window['go']['main']['App']['GetExtensionUpdates']();
}

export function GetExtensions() {
  return window['go']['main']['App']['GetExtensions']();
}

export function GetInstances() {
  return window['go']['main']['App']['GetInstances']();
}

export function GetJavaStatus() {
  return window['go']['main']['App']['GetJavaStatus']();
}

export function GetModLoaders() {
  return window['go']['main']['App']['GetModLoaders']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function InstallInstance(arg1) {
  return window['go']['main']['App']['InstallInstance'](arg1);
}

export function LaunchInstance(arg1) {
  return window['go']['main']['App']['LaunchInstance'](arg1);
}

export function LoginOffline(arg1) {
  return window['go']['main']['App']['LoginOffline'](arg1);
}

export function ReloadExtensions() {
  return window['go']['main']['App']['ReloadExtensions']();
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function ResolveExtensionConfirmation(arg1, arg2) {
  return window['go']['main']['App']['ResolveExtensionConfirmation'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectAndImportInstance() {
  return window['go']['main']['App']['SelectAndImportInstance']();
}

export function SelectAndInstallExtension() {
  return window['go']['main']['App']['SelectAndInstallExtension']();
}

export function SendExtensionMessage(arg1, arg2) {
  return window['go']['main']['App']['SendExtensionMessage'](arg1, arg2);
}

export function SetActiveAccount(arg1) {
  return window['go']['main']['App']['SetActiveAccount'](arg1);
}

export function StartMicrosoftAuth() {
  return window['go']['main']['App']['StartMicrosoftAuth']();
}

export function UninstallExtension(arg1) {
  return window['go']['main']['App']['UninstallExtension'](arg1);
}

export function UpdateExtension(arg1) {
  return window['go']['main']['App']['UpdateExtension'](arg1);
}

export function UpdateInstance(arg1) {
  return window['go']['main']['App']['UpdateInstance'](arg1);
}
